In [2]:
%load_ext autoreload
%autoreload 2

import os
import sys
sys.path.append(os.path.abspath(os.path.join('..')))

import pandas as pd
import numpy as np

train = pd.read_csv("../data/raw/train_BRCpofr.csv.zip", compression="zip")
test = pd.read_csv("../data/raw/test_koRSKBP.csv.zip", compression="zip")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
train.tail()

,id,gender,area,qualification,income,marital_status,vintage,claim_amount,num_policies,policy,type_of_policy,cltv
89387,89388,Male,Rural,High School,More than 10L,0,6,0,More than 1,B,Platinum,95736
89388,89389,Male,Urban,Bachelor,5L-10L,1,0,3897,More than 1,A,Platinum,67596
89389,89390,Female,Urban,Bachelor,5L-10L,0,4,3363,More than 1,B,Platinum,114120
89390,89391,Female,Rural,High School,2L-5L,0,8,0,More than 1,B,Platinum,71772
89391,89392,Female,Rural,High School,5L-10L,0,6,0,More than 1,B,Gold,108144

In [9]:
test.head()

,id,gender,area,qualification,income,marital_status,vintage,claim_amount,num_policies,policy,type_of_policy
0,89393,Female,Rural,High School,5L-10L,0,6,2134,More than 1,B,Silver
1,89394,Female,Urban,High School,2L-5L,0,4,4102,More than 1,A,Platinum
2,89395,Male,Rural,High School,5L-10L,1,7,2925,More than 1,B,Gold
3,89396,Female,Rural,Bachelor,More than 10L,1,2,0,More than 1,B,Silver
4,89397,Female,Urban,High School,2L-5L,0,5,14059,More than 1,B,Silver

In [10]:
train.shape, test.shape

((89392, 12), (59595, 11))

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89392 entries, 0 to 89391
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              89392 non-null  int64
 1   gender          89392 non-null  object
 2   area            89392 non-null  object
 3   qualification   89392 non-null  object
 4   income          89392 non-null  object
 5   marital_status  89392 non-null  int64
 6   vintage         89392 non-null  int64
 7   claim_amount    89392 non-null  int64
 8   num_policies    89392 non-null  object
 9   policy          89392 non-null  object
 10  type_of_policy  89392 non-null  object
 11  cltv            89392 non-null  int64
dtypes: int64(5), object(7)
memory usage: 8.2+ MB

In [18]:
train.tail(50)

,id,gender,area,qualification,income,marital_status,vintage,claim_amount,num_policies,policy,type_of_policy,cltv
89342,89343,Male,Urban,High School,More than 10L,1,1,12159,More than 1,A,Platinum,55608
89343,89344,Female,Urban,High School,2L-5L,1,0,2197,1,A,Platinum,30828
89344,89345,Male,Rural,Bachelor,5L-10L,1,3,3839,More than 1,A,Gold,56532
89345,89346,Male,Urban,High School,5L-10L,1,5,7677,More than 1,A,Platinum,109296
89346,89347,Male,Urban,Bachelor,5L-10L,1,5,0,1,B,Platinum,59484
89347,89348,Female,Urban,Bachelor,2L-5L,1,4,7934,More than 1,A,Gold,100272
89348,89349,Female,Urban,High School,5L-10L,1,3,0,More than 1,C,Platinum,350364
89349,89350,Male,Urban,Bachelor,5L-10L,1,2,2368,1,B,Silver,65256
89350,89351,Male,Rural,High School,More than 10L,0,6,0,1,B,Platinum,231672
89351,89352,Female,Rural,Others,5L-10L,1,6,3024,More than 1,B,Platinum,73656
89352,89353,Female,Urban,Others,2L-5L,1,8,0,1,B,Silver,52092
89353,89354,Female,Rural,Others,5L-10L,0,3,15361,More than 1,A,Platinum,66432
89354,89355,Male,Urban,High School,2L-5L,0,1,4395,1,B,Gold,69012
89355,89356,Male,Urban,High School,5L-10L,1,3,9577,More than 1,A,Platinum,293256
89356,89357,Female,Urban,High School,2L-5L,1,7,0,1,C,Silver,70488
89357,89358,Male,Urban,High School,5L-10L,0,6,12911,More than 1,A,Silver,88908
89358,89359,Female,Urban,High School,More than 10L,0,3,4583,More than 1,A,Silver,105084
89359,89360,Female,Urban,Bachelor,More than 10L,1,4,4018,1,A,Silver,62580
89360,89361,Male,Urban,Bachelor,2L-5L,1,7,6116,More than 1,A,Gold,66072
89361,89362,Male,Urban,Bachelor,2L-5L,1,7,5867,More than 1,A,Platinum,72720
89362,89363,Female,Rural,High School,5L-10L,0,0,0,More than 1,A,Platinum,65772
89363,89364,Male,Urban,Bachelor,5L-10L,1,6,0,More than 1,B,Silver,49368
89364,89365,Male,Rural,High School,5L-10L,1,8,0,1,A,Silver,64308
89365,89366,Male,Rural,Bachelor,5L-10L,0,3,0,More than 1,A,Platinum,67656
89366,89367,Male,Urban,High School,2L-5L,1,4,3814,More than 1,A,Platinum,59220
89367,89368,Female,Urban,High School,5L-10L,1,2,4249,More than 1,A,Platinum,67368
89368,89369,Female,Urban,Others,5L-10L,0,1,2219,1,B,Silver,31392
89369,89370,Female,Rural,Others,More than 10L,1,7,0,1,B,Platinum,34692
89370,89371,Female,Urban,Bachelor,2L-5L,1,6,3950,More than 1,B,Silver,74556
89371,89372,Male,Urban,Bachelor,5L-10L,1,8,17143,More than 1,A,Platinum,277056
89372,89373,Female,Urban,High School,5L-10L,0,3,5862,1,B,Silver,32904
89373,89374,Female,Urban,Bachelor,2L-5L,1,8,5365,More than 1,B,Platinum,276348
89374,89375,Female,Urban,High School,More than 10L,1,3,0,More than 1,C,Silver,148116
89375,89376,Male,Urban,High School,2L-5L,0,7,6483,More than 1,B,Silver,69900
89376,89377,Male,Rural,Bachelor,5L-10L,1,5,0,More than 1,A,Gold,123156
89377,89378,Female,Urban,High School,5L-10L,1,6,9154,More than 1,A,Platinum,67824
89378,89379,Male,Urban,High School,5L-10L,1,5,9505,More than 1,A,Gold,132864
89379,89380,Female,Rural,High School,5L-10L,0,5,0,1,B,Platinum,32472
89380,89381,Male,Urban,High School,2L-5L,1,1,9885,More than 1,A,Silver,164004
89381,89382,Female,Rural,Bachelor,5L-10L,0,1,6356,1,A,Silver,63300
89382,89383,Male,Urban,Bachelor,5L-10L,1,6,4168,More than 1,A,Platinum,73440
89383,89384,Female,Rural,High School,5L-10L,0,8,6664,More than 1,A,Silver,199056
89384,89385,Female,Rural,Bachelor,2L-5L,0,7,0,More than 1,B,Platinum,171828
89385,89386,Male,Urban,Bachelor,5L-10L,1,4,3138,More than 1,A,Gold,96672
89386,89387,Male,Urban,High School,5L-10L,1,0,5744,1,A,Platinum,59688
89387,89388,Male,Rural,High School,More than 10L,0,6,0,More than 1,B,Platinum,95736
89388,89389,Male,Urban,Bachelor,5L-10L,1,0,3897,More than 1,A,Platinum,67596
89389,89390,Female,Urban,Bachelor,5L-10L,0,4,3363,More than 1,B,Platinum,114120
89390,89391,Female,Rural,High School,2L-5L,0,8,0,More than 1,B,Platinum,71772
89391,89392,Female,Rural,High School,5L-10L,0,6,0,More than 1,B,Gold,108144

In [12]:
train.describe()

                 id  marital_status       vintage  claim_amount           cltv
count  89392.000000    89392.000000  89392.000000  89392.000000   89392.000000
mean   44696.500000        0.575488      4.595669   4351.502416   97952.828978
std    25805.391969        0.494272      2.290446   3262.359775   90613.814793
min        1.000000        0.000000      0.000000      0.000000   24828.000000
25%    22348.750000        0.000000      3.000000   2406.000000   52836.000000
50%    44696.500000        1.000000      5.000000   4089.000000   66396.000000
75%    67044.250000        1.000000      6.000000   6094.000000  103440.000000
max    89392.000000        1.000000      8.000000  31894.000000  724068.000000

In [15]:
train.nunique()

id                89392
gender                2
area                  2
qualification         3
income                4
marital_status        2
vintage               9
claim_amount      10889
num_policies          2
policy                3
type_of_policy        3
cltv              18796
dtype: int64